import { Box, Button, Paper, Stack, Typography } from '@mui/material';
import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import ProjectForm from '../../components/projects/ProjectForm';
import { createProject } from '../../services/projectService';

function CreateProject() {
  const navigate = useNavigate();
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState(null);

  const handleSubmit = async (payload) => {
    setSaving(true);
    setError(null);

    try {
      const result = await createProject(payload);
      navigate(`/projects/${result.project.id}`);
    } catch (caught) {
      setError(caught);
    } finally {
      setSaving(false);
    }
  };

  return (
    <Box>
      <Paper sx={{ p: 3, borderRadius: 3 }}>
        <Stack direction={{ xs: 'column', md: 'row' }} justifyContent="space-between" alignItems={{ xs: 'stretch', md: 'center' }} spacing={2} sx={{ mb: 3 }}>
          <Box>
            <Typography variant="h5" fontWeight={700}>Create Project</Typography>
            <Typography color="text.secondary">Project code is generated by the server after creation.</Typography>
          </Box>
          <Button variant="outlined" onClick={() => navigate('/projects')}>Back</Button>
        </Stack>
        <ProjectForm
          saving={saving}
          error={error}
          submitLabel="Create Project"
          onSubmit={handleSubmit}
        />
      </Paper>
    </Box>
  );
}

export default CreateProject;
